// Mocks generated by Mockito 5.4.6 from annotations
// in funday_flutter_interview/test/presentation/guide_spots_page/guide_spots_page_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:funday_flutter_interview/domain/repo/guide_spot_repository.dart'
    as _i2;
import 'package:funday_flutter_interview/domain/usecase/get_guide_spots_usecase.dart'
    as _i3;
import 'package:funday_flutter_interview/domain/value_object/guide_spot.dart'
    as _i5;
import 'package:funday_flutter_interview/fund/lang.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGuideSpotRepository_0 extends _i1.SmartFake
    implements _i2.GuideSpotRepository {
  _FakeGuideSpotRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGuideSpotsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGuideSpotsUsecase extends _i1.Mock
    implements _i3.GetGuideSpotsUsecase {
  MockGetGuideSpotsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GuideSpotRepository get guideSpotRepository =>
      (super.noSuchMethod(
            Invocation.getter(#guideSpotRepository),
            returnValue: _FakeGuideSpotRepository_0(
              this,
              Invocation.getter(#guideSpotRepository),
            ),
          )
          as _i2.GuideSpotRepository);

  @override
  _i4.Future<List<_i5.GuideSpot>> getGuideSpotsByPage({
    required _i6.Lang? lang,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGuideSpotsByPage, [], {
              #lang: lang,
              #page: page,
            }),
            returnValue: _i4.Future<List<_i5.GuideSpot>>.value(
              <_i5.GuideSpot>[],
            ),
          )
          as _i4.Future<List<_i5.GuideSpot>>);
}
