// Mocks generated by Mockito 5.4.6 from annotations
// in funday_flutter_interview/test/domain/usecase/get_guide_spots_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:funday_flutter_interview/domain/repo/guide_spot_repository.dart'
    as _i2;
import 'package:funday_flutter_interview/domain/value_object/guide_spot.dart'
    as _i4;
import 'package:funday_flutter_interview/fund/lang.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GuideSpotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuideSpotRepository extends _i1.Mock
    implements _i2.GuideSpotRepository {
  MockGuideSpotRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.GuideSpot>> getGuideSpots({
    required _i5.Lang? lang,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGuideSpots, [], {#lang: lang, #page: page}),
            returnValue: _i3.Future<List<_i4.GuideSpot>>.value(
              <_i4.GuideSpot>[],
            ),
          )
          as _i3.Future<List<_i4.GuideSpot>>);
}
